openapi: "3.0.3"
info:
  title: API with Authentification
  version: "1.0"
tags:
  - name: Products
    description: Operations related to products
  - name: Orders
    description: Operations related to orders

paths:
  /products:
    get:
      tags:
        - Products
      summary: Get list of products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                sample:
                  value:
                    - name: "Apple"
                      expiration_datetime: "2025-12-31T23:59:59Z"
                      price: 1200.5

  /orders:
    get:
      summary: Get list of orders
      tags:
        - Orders
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/SizeParam"
      responses:
        "200":
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
              examples:
                sample:
                  value:
                    - id: 1
                      customer_name: "Rakoto"
                      creation_datetime: "2025-08-25T17:11:00Z"
                      total_amount: 10000.0

    post:
      summary: Create a new order
      tags:
        - Orders
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
            examples:
              sample:
                value:
                  id: 1
                  customer_name: "Rasoa"
                  creation_datetime: "2025-09-01T12:00:00Z"
                  total_amount: 25000.5
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
              examples:
                sample:
                  value:
                    id: 2
                    customer_name: "Rakoto"
                    creation_datetime: "2025-09-01T12:00:00Z"
                    total_amount: 25000.5

components:
  parameters:
    PageParam:
      name: page
      in: query
      required: false
      schema:
        type: integer
        example: 2
    SizeParam:
      name: size
      in: query
      required: false
      schema:
        type: integer
        example: 10

  schemas:
    Product:
      type: object
      description: A Product Schema
      properties:
        name:
          type: string
          example: "Apple"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-12-31T23:59:59Z"
        price:
          type: number
          format: float
          example: 1200.5

    Order:
      type: object
      description: An Order Schema
      properties:
        id:
          type: integer
          example: 1
        customer_name:
          type: string
          example: "Rakoto"
        creation_datetime:
          type: string
          format: date-time
          example: "2025-08-25T17:11:00Z"
        total_amount:
          type: number
          format: float
          example: 10000.0

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
